title = "davegaeddert"
author = "Dave Gaeddert"
baseURL = "https://davegaeddert.com/"
languageCode = "en-us"
pygmentsuseclasses = false
googleAnalytics = "UA-54223125-1"

[permalinks]
fixed = ":title/"
blog  = ":slug/"

[params]
author = "Dave Gaeddert"
github = "//github.com/davegaeddert"
twitter = "//twitter.com/davegaeddert"
gravatar = "a2c58001a61d06c06f1c8b8a76953844"  # md5 of lower case email address
highlightjs = true
